User story AR-6
UB-ES-2022-A3/usArt pull request #192
Opened 2022-12-12 20:51 UTC by hectorhmartinez

## :page_facing_up: Resumen del trabajo hecho

Acabada AR-6
## :desktop_computer: Tipo de tarea
- [ ] Bug
- [ ] User story task
- [X] User story
- [ ] Code spike
- [ ] Hotfix

## :mag_right: Información adicional a tener en cuenta

## :disguised_face: Reviewers
[//]: # (Ejemplo: @jordiBujaldon @Manuel-AHA)

2022-12-13 10:14 UTC, Manuel-AHA requested changes
si entras en el perfil de alguien que has bloqueado sigue apareciendo un boton de block, en vez de unblock

Si tienes a alguien bloqueado puedes contactar a esa persona.

Si bloqueas a alguien no se borra el chat abierto con esa persona.

2022-12-14 19:48 UTC, hectorhmartinez commented
He hecho un GET extra en publicación para comprvar tmb si yo tengo bloqueado ese usuario. También he puesto un GET en callapi de profile para que mire si el botón tiene que ser 'Unblock' o 'Block' en el perfil. Finalmente, he hecho el delete del chat en backend cuando se bloquea a un usuario.

2022-12-15 12:06 UTC, rogeranyor approved these changes
👍

2022-12-15 12:07 UTC, Manuel-AHA approved these changes
Funciona todo, pasa las acceptance criteria

2022-12-15 12:07 UTC, merged