Get de detalle de publicación hecho ( U2-2 Crear GET de la publicacion)
UB-ES-2022-A3/usArt pull request #34
Opened 2022-10-26 19:12 UTC by gespinma12

2022-10-27 16:44 UTC, Manuel-AHA requested changes
Falta el atributo de imagenes (un array de referencas a las imagenes que tenga el producto), el atributo de review (un float entre 0 y 5, incluidos), el atributo de tipo de publicacion, la fecha de publicacion, y por ultimo, el id deberia ser una secuencia de caracteres 10 aleatoria.

2022-10-27 16:45 UTC, jordiBujaldon commented
Bona feina!! Codi molt net

2022-10-28 13:30 UTC, gespinma12 commented
Fet

2022-10-28 14:32 UTC, jordiBujaldon commented on usArt_backend/catalog/serializers.py
> +        fields = ("id", "title", "description", "author", "price", "image", "review")
Canviar "image" per "images"

2022-10-28 14:36 UTC, jordiBujaldon requested changes
Cal canviar el nom de les classes que tenen "Item" per "Publication"

2022-10-28 14:36 UTC, jordiBujaldon commented on usArt_backend/catalog/serializers.py
> +class ItemSerializer2(serializers.ModelSerializer):
Canviar ItemSerializer2 per PublicationSerializer

2022-10-28 15:56 UTC, gespinma12 reviewed
Fet

2022-10-29 16:44 UTC, Manuel-AHA approved these changes
El funcionamiento es correcto

2022-10-29 16:44 UTC, merged